#!/bin/sh
# Copyright 2011 Gilt Groupe, INC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

start() {
    # Set up the necessary yum repos and install puppet
    cp /etc/firstboot.d/data/xen.repo /etc/yum.repos.d/
    yum clean all 
    yum --disablerepo=citrix -y install puppet
    
    # Obtain the puppet.conf from the server and authorize this node
    #
    # Uncomment the line below in order to ensure you get a working puppet.conf
    # for Xenserver
    #wget -qO /etc/puppet/puppet.conf <CHANGE TO YOUR PUPPET MASTER IP HERE>/cblr/aux/xenserver/puppet.conf
    /usr/sbin/puppetd -o -v --waitforcert 600
}

case $1 in
  start) start ;;
esac


