#!/bin/sh
# Copyright 2011 Gilt Groupe, INC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -eu

LICENSE="${FIRSTBOOT_DATA_DIR}/license.xslic"

start() {
    if [ ! -f "/etc/license" ]; then
        # Or parse out $XE host-license-view
        if [ -e "$LICENSE" ]; then
            # if xslic exists, then add it
            $XE host-license-add host_uuid=$($XE host-list | sed -ne 's/^uuid .*: //p') license-file=$LICENSE
        fi
    fi
}

case $1 in
  start) start ;;
esac

