#!/bin/bash
# Copyright 2011 Gilt Groupe, INC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# XenServer post-install:
#   Hacked together from the standard ks
#   WARNING: post-install items are chrooted


# deine the chroot prefix for use below
CHROOT=/tmp/root


# Extract the necessary variables
server=$( grep DHCPACK /var/log/messages  | tail -1 | awk '{ print $NF }' )
system=$( hostname )
system=${system%%.*}
xenpath=cblr/aux/xenserver


### Prepare firstboot scripts for things that cannot be done with chroot

#   xenserver script and license file:
wget "http://$server/$xenpath/99-install-license" -O $CHROOT/etc/firstboot.d/99-install-license
wget "http://$server/$xenpath/license.xslic" -O $CHROOT/etc/firstboot.d/data/license.xslic

#   network configuration script and cobbler-retrieved interface scripts
#   Nov2010: bonding is disabled because it "gunks up" the pool according to AH, configure eth1 instead
wget "http://$server/$xenpath/99-configure-network" -O $CHROOT/etc/firstboot.d/99-configure-network
#wget "http://$server/cblr/svc/op/template/system/$system/path/_bond0" -O $CHROOT/etc/firstboot.d/data/configure_bond0.sh
wget "http://$server/cblr/svc/op/template/system/$system/path/_eth1" -O $CHROOT/etc/firstboot.d/data/configure_eth1.sh
wget "http://$server/cblr/svc/op/template/system/$system/path/_defgw" -O $CHROOT/etc/firstboot.d/data/default_gateway.sh

#   add i386 yum repos and have puppet installed/configured:
wget "http://$server/$xenpath/99-install-puppet" -O $CHROOT/etc/firstboot.d/99-install-puppet
wget "http://$server/cblr/svc/op/yum/system/$system" -O $CHROOT/etc/firstboot.d/data/xen.repo

#   all firstboot scripts should be executable
chmod +x $CHROOT/etc/firstboot.d/99-*


# Retrieve the virtual host manager used to dynamically provision virtual hosts using cobbler power template
wget "http://$server/$xenpath/virtualhost_manager.sh" -O $CHROOT/usr/local/bin/virtualhost_manager.sh
chmod +x $CHROOT/usr/local/bin/virtualhost_manager.sh


# Configure trusted root login
mkdir -m700 $CHROOT/root/.ssh
wget "http://$server/$xenpath/authorized_keys" 
cp authorized_keys $CHROOT/root/.ssh/
# End trusted login

# Configure ntp servers
wget "http://$server/$xenpath/ntp.conf" 
cp ntp.conf $CHROOT/etc/ntp.conf
# End configure ntp servers


# You can replace the default root password with something of your own choice
# by uncommenting out the line below and adding an appropriate md5 password hash
#sed -i -e 's!^root:[^:]*:!root:CHANGE_ME_TO_A_REAL_PASSWORD:!' $CHROOT/etc/passwd


# Lastly, disable pxe (disable netboot) for this host
wget -O /dev/null "http://$server/cblr/svc/op/nopxe/system/$system"


